### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by aratz-lasa** [rmies/monad#17]
Hi, it raises the following compilation error:

`== Compilation error in file lib/monad.ex ==
** (SyntaxError) lib/monad.ex:248: reserved token: __block__
    (elixir) lib/kernel/parallel_compiler.ex:229: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
could not compile dependency :monad, "mix compile" failed. You can recompile this dependency with "mix deps.compile monad", update it with "mix deps.update monad" or clean it with "mix deps.clean monad"
`

**Comment by lkuty** [comment]
The tests passed with success. I used Elixir v1.11.1

```
git clone ...
cd monad
mix deps.get
mix compile
mix test
```
